### ISSUE TITLE
Need subtitles for JavaScript Best Practices

### ISSUE THREAD

**Issue by aloayzab88** [codeschool/subtitles#19]
English is not my first language so it make things easier watching the videos with subs. 
Is there any update on the subs for the course  of JavaScript Best Practices?

**Comment by carloscarvallo** [comment]
Yes, that would be great if they had, because this stage is where they use some very technical language and speak up a bit fast. The English is not my native language and it is difficult to keep some parts.

**Comment by snychka** [comment]
This was done earlier this year, at the end of June!
