### ISSUE TITLE
Subs for Real-Time web with Nodejs

### ISSUE THREAD

**Issue by carloscarvallo** [codeschool/subtitles#20]
Nodejs is a fairly advanced and attractive language and it would be great to have subs for this course, the reason is because of the technical language required to understand depth concepts of that language. Thanks.

**Comment by matiasinsaurralde** [comment]
+1

**Comment by snychka** [comment]
They're there, although 4-7 are out of sync.  That's being worked on as we speak, so hopefully 4-7 are corrected soon!

**Comment by snychka** [comment]
Alright, 4-7 have been updated, so it's all good!

**Comment by abdoljabbar** [comment]
subtitle for level3 (stream) is out of sync.pleas update that.tnx in advance for ur amazing video

**Comment by snychka** [comment]
@abdoljabbar hmmm, yeah, you're right (and thanks Adam!)

Uncertain if the video changed, or I missed that when checking for out of sync ones.  Will get a task open for that.  Uncertain currently when that'll be completed, though

**Comment by snychka** [comment]
It's up there now
