### ISSUE TITLE
Subtitle for video [russian language]

### ISSUE THREAD

**Issue by XeL077** [codeschool/subtitles#25]
Hi, I love video courses Code School, and technologies like my friends. Many people in Russia has little understanding of English.

Can I or someone add subtitle translation in Russian to the repository through a pull requests?

**Comment by max-kovpak** [comment]
+1

**Comment by adamfortuna** [comment]
Hey hey! For translation requests, we're still working that into our flow and investigating how big the audience is for different languages. This is a pretttty big task considering how much content we have. 

For now though, we'd love to invite you to upvote the [Subtitles in other languages](https://codeschool.uservoice.com/forums/217988-feature-suggestions/suggestions/5113446-subtitles-in-other-languages) feature on UserVoice, which helps us prioritize this with other initiatives here at CS. Going to close this one out in favor of having it listed over in UserVoice -- but it's still on our radar to do for sure!

**Comment by paninRadario** [comment]
Okay, I will add pull-request

**Comment by XeL077** [comment]
Okay, I will add pull-request
