### ISSUE TITLE
English subtitles for Powering Up With React

### ISSUE THREAD

**Issue by cole-sanderson** [codeschool/subtitles#26]
I am Deaf and I depend on subtitles to understand videos. Would be awesome if you can add sometimes soon. Thanks!

**Comment by horahora** [comment]
I want it too!

**Comment by snychka** [comment]
Thanks for letting us know everyone!  For others coming to this, do a thumbs up on the original comment above by @cole-sanderson if you want subtitles as well.

A developer has just finished a long discussion with viddler where they both fixed things up so it's now possible for our newer courses, a lot of movement overall has happened in the last week, and I'll be meeting with the two here who normally do subtitles tomorrow so quicker progress soon is likely.

Oh, and the subtitles for the first video at least are there now, too!

**Comment by snychka** [comment]
Sorry for the delay.  Subtitles are very time-consuming to do, but we're all good to go now!  A nice team effort here.

**Comment by cole-sanderson** [comment]
@snychka thanks! 😃
