### ISSUE TITLE
Subtitles translations from Brazilian Portuguese progress

### ISSUE THREAD

**Issue by ricardovsilva** [codeschool/subtitles#29]
This is the running list of which courses need translation and which courses are already translated. Updated as progress is made.

**Legacy Courses**
- [ ] A Sip of CoffeeScript
- [ ]  Anatomy of Backbone.js
- [ ]  Anatomy of Backbone.js Part 2
- [ ]  Assembling Sass Part 1
- [ ]  Assembling Sass Part 2
- [ ]  CSS Cross-Country
- [ ]  Discover DevTools
- [ ]  Front-end Formations
- [ ]  Fundamentals of Design
- [ ]  Git Real 1
- [ ]  Git Real 2
- [ ]  JavaScript RoadTrip 1
- [ ]  JavaScript RoadTrip 2
- [ ]  JavaScript RoadTrip 3
- [X]  Journey Into Mobile
- [ ]  Rails 4: Patterns
- [ ]  Rails 4: Zombie Outlaws
- [ ]  Rails Best Practices
- [ ]  Rails For Zombies
- [ ]  Rails For Zombies 2
- [ ]  Rails Testing for Zombies
- [ ]  RubyBits 1
- [ ]  RubyBits 2
- [ ]  Surviving APIs with Rails
- [ ]  Testing with RSpec
- [ ]  Try iOS
- [ ]  Try jQuery
- [ ]  iOS: Operation MapKit
- [ ]  iOS: Operation Models
- [ ]  jQuery: The Return Flight
- [ ]  Warming up With Ember.js

**Campus Courses**
- [ ]  Accelerating Through Angular 2
- [ ]  Adventures in Web Animations
- [ ]  App Evolution with Swift
- [ ]  Blasting Off with Bootstrap
- [ ]  Breaking the Ice with Regular Expressions
- [ ]  Building Blocks for Express.js
- [ ] Discover Drive
- [ ]  ES2015: The Shape of JavaScript to Come
- [ ]  Flying Through Python
- [ ]  Front-end Foundations
- [ ]  JavaScript Best Practices
- [ ]  Mastering Github
- [ ]  Powering Up with React
- [ ]  Real-time Web with Node.js
- [ ]  Level 3 (of Real-time Web with Node.js)
- [ ]  Shaping up with Angular.js
- [ ]  Staying Sharp with Angular.js
- [ ]  The Elements of Web Design
- [ ]  The Magical Marvels of MongoDB
- [ ]  The Sequel to SQL
- [ ]  Try .NET MVC
- [ ]  Try Django
- [ ]  Try Ember
- [ ]  Try Python
- [ ]  Try SQL
- [ ]  Unmasking HTML Emails
- [ ]  You, Me, & SVG

**Comment by snychka** [comment]
No progress on this recently, so closing.

Please re-open if you are going to work on it some more!
