### ISSUE TITLE
Angular 2 course subtitle not consistent

### ISSUE THREAD

**Issue by arntj** [codeschool/subtitles#32]
It seems to me like the Angular 2 subtitles are completed. But many of the videos don't have subtitles enabled in the web player. It seems inconsistent, some course videos have subtitles available and some don't in the web player.

**Comment by snychka** [comment]
Thanks!  The course was updated, and the video-subtitles need to still be updated.  It's being worked on, and I hope will be done soon!

**Comment by snychka** [comment]
Updated!
