### ISSUE TITLE
Discover DevTools

### ISSUE THREAD

**Issue by aimeesimone** [codeschool/subtitles#8]
The subtitles for [Level 1](http://discover-devtools.codeschool.com/chapters/1/challenges/1?locale=en) are out of sync. I think the [subtitle file](https://github.com/codeschool/subtitles/blob/master/discover-devtools/1-a-en.srt) is just missing the intro jingle. @christinewong can you look into this?

**Comment by bijanbwb** [comment]
I finally managed to fix this. It's updated and deployed so the Level 1 subtitles should sync up properly now.
